import { GetServerSideProps } from "next";
import Head from "next/head";
import { useEffect } from "react";
import Cookies from "js-cookie";

export default function Login() {
  useEffect(() => {
    Cookies.set('token', '123456789abcdef')
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>LOGİN</main>
    </>
  );
}
